name: Daily Smart Contract Checks

on:
  schedule:
    - cron: '0 5 * * *'  # Run at 7 AM Warsaw time (UTC+2)
  workflow_dispatch:  # Allow manual triggering

env:
  CONTRACT_ADDRESS: '0x26f36F365E5EB6483DF4735e40f87E96e15e0007'
  TREASURY_ADDRESS: '0xBADfB4AdCF5ADB939B25fba58db544860c45A1e5'

jobs:
  check-contract:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Create environment files
        run: |
          printf "%s" "${{ secrets.TWITTER_VERIFICATION_ENV }}" > ./web3-functions/twitter-verification/.env
          printf "%s" "${{ secrets.TWITTER_WORKER_ENV }}" > ./web3-functions/twitter-worker/.env
          printf "%s" "${{ secrets.TWITTER_WORKER_PROD_ENV }}" > ./web3-functions/twitter-worker/prod.env
          printf "%s" "${{ secrets.TEST_ENV }}" > ./test/.env

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          npm test > test-results.txt 2>&1 || true
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
          if-no-files-found: error

      - name: Check smart contract events
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TEST_STATUS: ${{ steps.tests.outputs.status }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
          TWITTER_HOST: ${{ secrets.TWITTER_HOST }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_SERVER_NAME: ${{ secrets.TWITTER_SERVER_NAME }}
        run: node .github/workflows/check-contract.js 