name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
      run_coverage:
        description: 'Run with coverage report'
        required: false
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create environment files
        run: |
          printf "%s" "${{ secrets.TWITTER_VERIFICATION_ENV }}" > ./web3-functions/twitter-verification/.env
          printf "%s" "${{ secrets.TWITTER_WORKER_ENV }}" > ./web3-functions/twitter-worker/.env
          printf "%s" "${{ secrets.TWITTER_WORKER_PROD_ENV }}" > ./web3-functions/twitter-worker/prod.env
          printf "%s" "${{ secrets.TEST_ENV }}" > ./test/.env

      - name: Run tests with coverage
        id: test-run
        run: |
          yarn coverage > test-output.log 2>&1
          echo "status=$?" >> $GITHUB_OUTPUT
          # Extract coverage percentage
          COVERAGE=$(grep -o "Statements.*%" coverage/coverage-summary.json | grep -o "[0-9]*\.[0-9]*%" | head -1)
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Upload coverage log
        uses: actions/upload-artifact@v4
        with:
          name: coverage-log
          path: |
            coverage.log
            test-output.log
          retention-days: 14

      - name: Set job status
        if: always()
        run: |
          if [[ "${{ steps.test-run.outputs.status }}" == "0" ]]; then
            exit 0
          else
            exit 1
          fi

      - name: Debug Event Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Ref: ${{ github.ref }}"

      - name: Comment PR
        if: ${{ github.event.pull_request }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testStatus = '${{ steps.test-run.outputs.status }}' === '0' ? '✅ PASSED' : '❌ FAILED';
            const coverage = '${{ steps.test-run.outputs.coverage }}';
            const testOutput = fs.readFileSync('test-output.log', 'utf8');
            const failedTests = testOutput.match(/FAIL.*\n.*\n.*/g) || [];
            
            let comment = `## Test Results\n\n`;
            comment += `### Status: ${testStatus}\n\n`;
            comment += `### Coverage: ${coverage}\n\n`;
            
            if (failedTests.length > 0) {
              comment += `### Failed Tests:\n\`\`\`\n${failedTests.join('\n')}\n\`\`\`\n\n`;
            }
            
            comment += `### Full Test Output\n\`\`\`\n${testOutput}\n\`\`\``;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });